name: Get the build DLL

on:
  push:
    branches: [ master ] 
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      MAJOR_VERSION: 6
      MINOR_VERSION: 0
      SOLUTION_PATH: ./src/6.0/
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x    
    - name: Remove annotations
      run: echo "::remove-matcher owner=csc::"
    - name: Install specflow-to-markdown tool
      run: dotnet tool install -g Gman.SpecFlowToMarkdown  
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build $SOLUTION_PATH --no-restore --ignore-failed-sources -c Release
    - name: Test
      run: dotnet test $SOLUTION_PATH --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Artifact
        path: ./src/